version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana2
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus2
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  streamlit_app:
    build:
      context: ./webapp
    ports:
      - "8501:8501"
    depends_on:
      - fastapi_app

  fastapi_app:
    build:
      context: ./serving
    volumes:
      - ./artifacts:/artifacts
    ports:
      - "8080:8080"

volumes:
  grafana-data:
  prometheus-data:
  